# Generated by Django 3.0.3 on 2020-05-12 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='adding_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
